feature - colab
ZenGuard-AI/fast-llm-security-guardrails pull request #34
Opened 2024-05-30 10:46 UTC by ThiagoRouge

2024-05-31 02:55 UTC, baur-krykpayev requested changes

2024-05-31 02:55 UTC, baur-krykpayev commented on zenguard_library.ipynb
lets put this into the docs/colabs/ folder

2024-05-31 02:55 UTC, baur-krykpayev commented on zenguard_library.ipynb
> +          "text": [
do we really need to have outputs here? especially the ones that just download stuff?

2024-05-31 02:55 UTC, baur-krykpayev commented on zenguard_library.ipynb
> +          "base_uri": "https://localhost:8080/"
what is this?

2024-05-31 02:56 UTC, baur-krykpayev commented on zenguard_library.ipynb
> +        "ZENGUARD_API_KEY=\"\""
can we setup API key from OS env? instead of having it being displayed in the open as it is now?

2024-05-31 09:44 UTC, ThiagoRouge commented on zenguard_library.ipynb
> +          "base_uri": "https://localhost:8080/"
If I'm mistaken, he was running docker

2024-06-02 19:05 UTC, baur-krykpayev approved these changes

2024-06-02 19:10 UTC, merged